workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fully initialize app
        script: flutter create .

      - name: Install dependencies
        script: flutter pub get && flutter pub run flutter_launcher_icons:main
    
       - name: Install certificate and provisioning profile
         script: |
           security create-keychain -p "temp" ios-build.keychain
           security default-keychain -s ios-build.keychain
           security unlock-keychain -p "temp" ios-build.keychain

           security import certs/ios_distribution.p12 -k ios-build.keychain -P "1" -T /usr/bin/codesign

           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
           cp certs/provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

       - name: Build signed IPA
         script: |
            flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist

            
    artifacts:
      - build/ios/ipa/*.ipa
