workflows:
  build-ios-app:
    name: Build Unsigned iOS App (.app)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: initial Creation
        script: flutter create .
        
      - name: Install Flutter packages
        script: |
          flutter pub get

      - name: Build iOS unsigned .app
        script: |
          flutter build ios --release --no-codesign

      - name: Zip Runner.app
        script: |
          cd build/ios/iphoneos
          zip -r Runner.zip Runner.app
          mv Runner.zip ../../../Runner.zip

    artifacts:
      - Runner.zip
