workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Fully initialize app
        script: flutter create .

      - name: Build unsigned IPA
        script: flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
