workflows:
  build-macos-app:
    name: Build macOS .app
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: initial Creation
        script: flutter create .
        
      - name: Enable macOS desktop
        script: flutter config --enable-macos-desktop
        
      - name: Get dependencies
        script: flutter pub get
        
      - name: Build macOS app
        script: flutter build macos --release
        
    artifacts:
      - build/macos/Build/Products/Release/*.app
