workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get && flutter pub run flutter_launcher_icons:main

      - name: Fully initialize app
        script: flutter create .

      - name: Build unsigned IPA
        script: flutter build ipa --no-codesign

      - name: Export IPA manually from archive
        script: |
          mkdir -p build/ios/ipa
          xcrun xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
