workflows:
  build_and_package:
    name: Build macOS app and create DMG
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: initial creation
        script: flutter create .

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Enable macOS desktop
        script: |
          flutter config --enable-macos-desktop

      - name: Build .app
        script: |
          flutter build macos --release

      - name: Create .dmg
        script: |
          cd build/macos/Build/Products/Release
          hdiutil create -volname "RiddleRealms" \
            -srcfolder "riddle_realms.app" \
            -ov -format UDZO RiddleRealms.dmg

    artifacts:
      - build/macos/Build/Products/Release/RiddleRealms.dmg
