name: riddle_realms
description: A simple riddle app using Pollinations.ai TTS

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  audioplayers: ^5.2.1

flutter:
  uses-material-design: true
