name: riddle_realms
version: 1.0.0
summary: Riddle Realms Flutter App
description: |
  Riddle Realms is a poetic riddle app built using Flutter.
arch: x86_64
category: utility
maintainer: Cool Geek <you@example.com>
license: MIT
depends:
  - libgtk-3-0
