name: Build Flutter Windows App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'

    - name: initial Creation
      run: flutter create .

    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop

    - name: Get dependencies
      run: flutter pub get

    - name: Build Windows Release
      run: flutter build windows --release

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: build/windows/x64/runner/Release/*.exe
