name: Build Linux Packages

on:
  push:
    branches: [main]

jobs:
  package-linux:
    name: Package for Linux (.rpm, .AppImage, .snap, .flatpak)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: initial creation
        run: flutter create .

      - name: Enable Linux support
        run: flutter config --enable-linux-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-3-dev libglib2.0-dev \
            fuse libfuse2 patchelf \
            rpm flatpak snapcraft \
            desktop-file-utils squashfs-tools

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build all Linux packages
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutter_distributor package --platform linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: build/distribute/linux/**
