name: Build Linux tar.gz Package

on:
  push:
    branches:
      - main

jobs:
  build-tarball:
    name: Build .tar.gz on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: initial creation
        run: flutter create .

      - name: Enable Linux desktop support
        run: flutter config --enable-linux-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter app for Linux
        run: flutter build linux --release

      - name: Create tar.gz package
        run: |
          mkdir output
          tar -czvf output/myapp-linux.tar.gz -C build/linux/x64/release/bundle .

      - name: Upload tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-tarball
          path: output/myapp-linux.tar.gz
